### ISSUE TITLE
streamsupport-1.5.4 is available

### ISSUE THREAD

**Issue by stefan-zobel** [streamsupport/streamsupport#11]
Hi Andrew,

I've just released streamsupport 1.5.4. Maybe you might want to update.

There are no structural changes or additions but note that I've now added
the general "Readme.txt" directly under the root. The "Readme.txt" has quite
a lot of changes, so maybe you want to pick up the changes from there.

Thanks in advance,
Stefan

**Comment by yongjhih** [comment]
Hi @stefan-zobel,

Thanks for informing, I've updated: https://github.com/streamsupport/streamsupport/releases/tag/1.5.4

**Comment by stefan-zobel** [comment]
Hi Andrew,

wow, this was super duper fast!
Thanks a lot!!

Kind regards,
Stefan

**Comment by stefan-zobel** [comment]
I think this can be closed then, or do you think there's still something you want to do?
Otherwise, feel free to close.

Kind regards;
Stefan
