### ISSUE TITLE
Separate java8.util.function.* into its own module?

### ISSUE THREAD

**Issue by aaronhe42** [streamsupport/streamsupport#18]
Like `streamsupport:streamsupport-functions-backport`?

It'd be very useful for people who only want to have those functional interfaces but not the entire streams backport library. Especially in the Android land, we can take advantage of desugar to have lambdas without bringing the entire streams library.

**Comment by stefan-zobel** [comment]
You are probably looking for https://github.com/ipcjs/java-support

Does that fit your need?

--Stefan

**Comment by aaronhe42** [comment]
yeah, looks like that's exactly what I need. Thanks!
