### ISSUE TITLE
Wrong tag for the 1.4.1 release

### ISSUE THREAD

**Issue by stefan-zobel** [streamsupport/streamsupport#2]
Hi Andrew,

you have the 1.4.1 tag on the wrong changeset.

Your tag is on changeset a12682efbe4cd9c5a64b9763c15c480bed29f67c from 09.02.16 which is only two commits away from the 1.4.2 release.
The correct changeset for 1.4.1 is 7ab9dda6fa863681bedc1497cddc72e0bb2622b0 from 26.12.2015.

If you want your project to be a mirror, then you'd better make sure that you are actually mirroring - not contriving releases that never existed.

Please fix this for the collective good.

Regards,
Stefan

**Comment by yongjhih** [comment]
Ok, it's my mistake. Now, it's been fixed. Thanks.

**Comment by stefan-zobel** [comment]
Thanks,
Stefan
