### ISSUE TITLE
I have a question about streamsupport(1.6)

### ISSUE THREAD

**Issue by ZBHdd** [streamsupport/streamsupport#21]
there is a error when I  build the project.

无法将接口 java8.util.stream.Stream<T>中的方法 map应用到给定类型;
[ERROR]   需要: java8.util.function.Function<? super java.lang.Object,? extends R>
[ERROR]   找到: <匿名java8.util.function.Function<java.lang.Integer,java.lang.String>>
[ERROR]   原因: 不存在类型变量R的实例, 以使参数类型<匿名java8.util.function.Function<java.lang.Integer,java.lang.String>>与形式参数类型java8.util.function.Function<? super java.lang.Object,? extends R>一致,

jdk is 1.7. It's okay to run and compile.
the code is 

![xxplhu2r6p2o9u7 r 57oqf](https://user-images.githubusercontent.com/30063654/34668579-00aeea66-f4a9-11e7-8259-0a4e67e44064.png)

I want to know what to do and why this error occurred? thanks

**Comment by ZBHdd** [comment]
There is no instance of the type variable R, so that the parameter type < anonymous java8. Util. The function. The function < Java. Lang. Integer, Java. Lang. String > > and formal parameter type java8. Util. The function. The function <?Super Java. Lang. Object,?Extends R > consistent

**Comment by stefan-zobel** [comment]
I cannot reproduce, sorry. Works fine for me with javac from Oracle JDK 1.8.0_51.
What compiler do you use?

**Comment by ZBHdd** [comment]
jdk 1.7
https://github.com/streamsupport/streamsupport
streamsupport is a backport of the Java 8 java.util.function (functional interfaces) and java.util.stream (streams) API for users of Java 6 or 7 supplemented with selected additions from java.util.concurrent which didn't exist back in Java 6.
Can't I use 'streamsupport' in jdk1.7?thanks

**Comment by stefan-zobel** [comment]
Sorry, I missunderstood you. Of course, you can use streamsupport with jdk 1.7 (or jdk 1.6).

But you'll have to be prepared that type inference in those older compilers is not up to par with Java 8 / Java 9 compilers.
So, sometimes a statement / expression that compiles with 8 can't be compiled unchanged with 6 or 7.

Providing a type witness helps often. Sometimes, you'll have to give up fluent style and break up the statement / expressions into different parts.

E.g., separating out the 

		Stream<Integer> stream = RefStreams.iterate(0, new UnaryOperator<Integer>() {
			@Override
			public Integer apply(Integer n) {
				return n + 1;
			}
		});

part would help in your case.

I'll see whether I can find another solution later.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
I would do it this way:

		List<String> list = RefStreams.<Integer, Integer>iterate(0, new UnaryOperator<Integer>() {
			@Override
			public Integer apply(Integer n) {
				return n + 1;
			}
		}).limit(10000).map(new Function<Integer, String>() {
			@Override
			public String apply(Integer n) {
				return String.format("%04d", n);
			}
		}).collect(Collectors.<String>toList());


Note the two type witnesses:

RefStreams.<**Integer, Integer**>iterate and Collectors.<**String**>toList. The first is there to help the compiler infer the correct type for the _map_ call and the second is there so that the result is correctly inferred as _List<**String**>_ instead of _List<**Object**>_.

This works for me with javac from Oracle JDK 1.7.0_80. Be prepared to apply such workarounds to help the compiler figure out the correct types in Java 6 / 7.

Regards,
Stefan

**Comment by ZBHdd** [comment]
Thank you for doubts

**Comment by stefan-zobel** [comment]
You're welcome.

I've also answered your corresponding question on stackoverflow: https://stackoverflow.com/questions/48149940/streams-backport-compile-error

Regards,
Stefan
