### ISSUE TITLE
streamsupport 1.6.1 / 1.6.2 released

### ISSUE THREAD

**Issue by stefan-zobel** [streamsupport/streamsupport#22]
Hi Andrew, @yongjhih

I've just released streamsupport 1.6.1.
Maybe you might want to update when you have time.

Thanks in advance & kind regards,
Stefan

**Comment by stefan-zobel** [comment]
Andrew,

sorry, I forgot to mention: **streamsupport-literal** has been discontinued in release 1.6.1 (since the API has already been merged into the core streamsupport.jar in 1.6.0).

Thus, there is no "streamsupport-literal-1.6.1" artifact to deploy (but the code still exists in the repo, of course).
However, streamsupport-literal-1.6.0 can still be used along newer versions of the other components since it hasn't any dependencies on other streamsupport components.

Thought I'll add that just in case you or anyone else starts to wonder.

Regards,
Stefan

**Comment by yongjhih** [comment]
@stefan-zobel 
Hi Stefan, I think I can do it this weekend. Yes, I am working on a sort of weighty things and had a Lunar New Year, thanks for asking.

**Comment by stefan-zobel** [comment]
Just FYI, streamsupport has moved to GitHub in the meanwhile: https://github.com/stefan-zobel/streamsupport
The 3 weeks downtime on sourceforge was just unbearable.

Regards,
Stefan
