### ISSUE TITLE
Error: null, Cannot fit requested classes in a single dex file (# methods: 67006 > 65536)

### ISSUE THREAD

**Issue by vikash159** [streamsupport/streamsupport#25]
just implemented 
implementation 'net.sourceforge.streamsupport:streamsupport:1.6.2'
even tried lower version, but getting error during build

Error: null, Cannot fit requested classes in a single dex file (# methods: 67006 > 65536)
Cannot fit requested classes in a single dex file (# methods: 67006 > 65536)

**Comment by retrostreams** [comment]
https://developer.android.com/studio/build/multidex.html#mdex-gradle

**Comment by vikash159** [comment]
resolved issue by updating min sdk level to 21 without enabling multiDex
