### ISSUE TITLE
Please update to 1.5-stable

### ISSUE THREAD

**Issue by stefan-zobel** [streamsupport/streamsupport#3]
Hi Andrew,

I've released streamsupport **1.5** a few hours ago. Maybe you might want to update.

Please note that I've added a new (optional) component named "streamsupport-literal".

This contains the the implementation for JEP 269: Convenience Factory Methods for Collections
(see http://openjdk.java.net/jeps/269)

Thanks,
Stefan

**Comment by yongjhih** [comment]
Updated: https://github.com/streamsupport/streamsupport/releases/tag/1.5

Good job.

**Comment by stefan-zobel** [comment]
Thanks a lot, Andrew!

Kind regards,
Stefan
