### ISSUE TITLE
1.5.1-stable is available

### ISSUE THREAD

**Issue by stefan-zobel** [streamsupport/streamsupport#5]
Hi Andrew,

streamsupport-1.5.1 has been released (no structural changes or additions this time). Maybe you might want to update.

Thanks,
Stefan

**Comment by yongjhih** [comment]
https://github.com/streamsupport/streamsupport/tree/1.5.1

**Comment by stefan-zobel** [comment]
Wow, that was fast. Thanks a lot, Andrew!

Kind regards,
Stefan
